# Generated by Django 2.1 on 2018-09-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image', models.URLField()),
                ('image_small', models.URLField()),
                ('categories', models.ManyToManyField(related_name='products', to='healthier_food.Category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
